mysqldb:
  image: mysql:latest
  environment:
    MYSQL_DATABASE: bob
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: supersecret
mywildfly:
  image: mcupak/bob:latest
  links:
    - mysqldb:db
  ports:
    - 8080:8080
    - 9990:9990
