version: '2.0'

services:
  mysql:
    image: mysql:5.7.11
    environment:
      MYSQL_DATABASE: bob
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: supersecret
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
  bob:
    build:
      context: bob
    image: mcupak/bob:latest
    volumes:
      - bob_log:/opt/jboss/wildfly/standalone/log
    expose:
      - 8080
      - 9990
    links:
      - mysql
  httpd:
    build:
      context: httpd
    image: mcupak/httpd:latest
    links:
      - bob
    external_links:
      - beaconizer
    ports:
      - 80:80
      - 443:443

volumes:
  mysql_data:
  bob_log:
